version: '3'

volumes:
  mongo_data:

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  mongo-admin:
    container_name: mongo-admin
    image: mrvautin/adminmongo:latest
    restart: "always"
    links:
      - mongo
    environment:
      - CONN_NAME=demo-admin
      - DB_HOST=mongo
      - DB_PORT=27017
      - HOST=0.0.0.0
    ports:
      - 1234:1234
